### ISSUE TITLE
Design: Upgrading Contracts

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#15]
We don't have a good story for how we'll handle contract (e.g. BountyRegistry) upgrades.

Thankfully, our friends at Trail of Bits have done a lot of thinking on this front.

Here's what they say not to do: https://blog.trailofbits.com/2018/09/05/contract-upgrade-anti-patterns/

They are preparing a post on what to do based on experience with auditing Gemini Dollar.

**Comment by myhndl** [comment]
Applying Blocker label. We need a way to (re-)deploy contracts in testnets in a sane-enough manner on sidechains we control ASAP, to discuss tomorrow.

**Comment by ceseale** [comment]
The contract part of this is handled above so now new contracts will be deployed on seeing a difference in contract code. Polyswarmd might still have to be manually restarted until hot-reloading is added.

**Comment by myhndl** [comment]
Closed via: https://github.com/polyswarm/development-private/issues/80
