### ISSUE TITLE
Design: offers transport

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/development#18]
Currently offers are routed between users through polyswarmd through a series of websockets, this shouldn't be a requirement. Ticket tracks investigating other transport options.

**Comment by myhndl** [comment]
We decided on:
* offer channels are websockets
* Expert is responsible for opening a port
* (hosted) polyswarmd makes Ambassador aware of the Expert's websocket endpoint
* this traffic will no traverse polyswarmd
