### ISSUE TITLE
Migrate Issues to polyswarm-client

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#20]
**Is your feature request related to a problem? Please describe.**
Open Issues in Archived repositories appear as suggested Issue cards in GitHub Projects. There's no way to remove them short of closing them. There's no way to close them while the project is archived.

**Describe the solution you'd like**
Migrate issues & close all Issues from `arbiter`, `microengine` and `ambassador` to `polyswarm-client`.

**Comment by mjkoo** [comment]
Ported over relevant issues, most had been already addressed. Cannot close issues on the archived projects so they remain open.

**Comment by myhndl** [comment]
Closed the issues; have we incorporated pull requests as well?
* https://github.com/polyswarm/ambassador/pull/1
* https://github.com/polyswarm/microengine/pull/26

**Comment by mjkoo** [comment]
Can close polyswarm/microengine#26, I'll get polyswarm/ambassador#1 or something similar incorporated now

**Comment by myhndl** [comment]
When something similar is incorporated, let's close this and thank the pull requester.

**Comment by mjkoo** [comment]
polyswarm/polyswarm-client#31 addresses this
