### ISSUE TITLE
Alerting: Container Shutdowns & Restarts

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#23]
**Is your feature request related to a problem? Please describe.**
We need a proactive alert for when containers unexpectedly shutdown and restart.

**Describe the solution you'd like**
Enumerate all manner in which containers *expect* to restart. Author a Datadog alert on all other cases.

**Comment by mb2con** [comment]
No built in stat to monitor if a container has restarted.  There is an option to get the stopped container.  I can make an alert to see if/when a running container as stopped.

**Comment by mb2con** [comment]
there is still no way to see if a container restart.  Docker events wont explicitly say when a container restarts. We'll have to find another metric to track.  Monitoring processes might be a better option.

**Comment by mb2con** [comment]
We can alert on the host but not a container.  We'll have to look at other options on how to get an alert of complete container restart.

**Comment by myhndl** [comment]
Set up alerts for Error level messages from Docker on DataDog. This includes forceful (kill) termination of containers. This serves this ticket sufficiently for the moment with this caveat: https://github.com/polyswarm/development-private/issues/45
