### ISSUE TITLE
consumer: a Results Caching Service

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#26]
**Is your feature request related to a problem? Please describe.**
We need rapid responses regarding artifacts that have already been seen by the network.

**Describe the solution you'd like**
A caching service that accepts artifacts for scanning, immediately returns a cached result if one exists, otherwise submits the artifact to `polyswarm-client` for investigation by the market.

If the response is cached, it should also be noted as such so the user can request a cache eviction and re-scan.

**Additional context**
Related / similar to: https://github.com/polyswarm/development-private/issues/34

**Comment by myhndl** [comment]
Useful as basis for larger archival service.

**Comment by Rizato** [comment]
Consumer does have some measure of caching in redis, though it doesn't allow forced eviction yet. Basically, it runs sha256 on each file, and then uses that to find the file in redis. The keys related to that file track all assertions, votes, and ground truth related to the file. 

If someone submits a set of files, any duplicates are excluded from the bounty, but the submission will still be notified on any assertions/votes/whatever on the excluded files.

**Comment by myhndl** [comment]
This is now being developed in consumer: https://github.com/polyswarm/consumer

Closing this ticket, please track issues with consumer in it's project.
