### ISSUE TITLE
Alerting: Bounty Asserts Stop Happening

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#31]
**Is your feature request related to a problem? Please describe.**
We need to know ASAP if bounties are no longer being asserted on.

**Describe the solution you'd like**
A Datadog monitor that triggers if bounty asserts drop to 0 over some time period. This is needed on both production and staging.

**Comment by mb2con** [comment]
Home chain asserts are being graphed in the polyswarm dashboard currently.  the side chain asserts and settles metric is missing at this point.  No idea why.  investigating.....

**Comment by mb2con** [comment]
There is a bug in the poly-mon code for the stage metric.  I think its around line 172 in https://github.com/polyswarm/poly-mon/blob/master/src/poly_mon/__init__.py.  Not sure how to fix it @scsich

**Comment by mb2con** [comment]
I could be wrong of course.

**Comment by myhndl** [comment]
@mb2con where exactly do you suspect there's a bug? Please always specify exact line and commit, a la: https://github.com/polyswarm/poly-mon/blob/f80c8fdd85a06281673cef54345c9066c7273235/src/poly_mon/__init__.py#L172

**Comment by mb2con** [comment]
https://github.com/polyswarm/poly-mon/blob/f80c8fdd85a06281673cef54345c9066c7273235/src/poly_mon/__init__.py#L270

I believe that is is just looking at the home chain. I dont know python at all so its my best guess.

**Comment by myhndl** [comment]
Applying bug and blocker because this is blocking us from getting some metrics.

**Comment by myhndl** [comment]
That doesn't look buggy to me, but the larger issue here is I don't think we're actually doing any sidechain bounty settles or asserts yet. 

Questions:
1. @mb2con have you seen some metrics come through and it's graphing it wrong or something?
2. We're effectively not doing anything on the sidechain at the moment, right @ceseale ?

**Comment by mb2con** [comment]
https://github.com/polyswarm/development-private/issues/51
https://github.com/polyswarm/poly-mon/issues/6
https://github.com/polyswarm/development/issues/51

These are all the same issue.  There is a problem with poly-mon and the polyswarm.side.bounty_settles, and polyswarm.side.bounty_asserts metrics that were working in DD a long time ago.  Polyswarm.home.bounty_settles and asserts exist on the other hand.  

I believe it has to do with this commit Steve pushed 
https://github.com/polyswarm/poly-mon/commit/cce24b0c2f11649f05e842ff61620289a243b72c#diff-1509ed4d82e814a3787b752b3886cfa2

**Comment by ceseale** [comment]
No assertions on sidechain is expected since we aren't doing anything on it yet. I'm going to try sending some across to test.

**Comment by myhndl** [comment]
@ceseale did you send txns across?

**Comment by myhndl** [comment]
Settle events are being tracked, which includes assertions.

Between that and this: https://github.com/polyswarm/development-private/issues/98, we're good here.
