### ISSUE TITLE
arbiter-cuckoo Needs More Time to Respond

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#35]
**Describe the bug**
On testnets, ground truth window is currently 100 blocks. Each block is 1s. 

This is insufficient time for Cuckoo to respond appropriately; they need on the order of minutes. They've simply been returning a random answer for testing.

**Expected behavior**
Low block time and ground truth window help with testing, so maybe we retain 100 block window on Staging, increase to 20 minutes (~1000 blocks) on Production?

**Comment by myhndl** [comment]
@mjkoo @Rizato @ceseale  do you have any thoughts on this one? Should we just increase ground truth period in both envs?

**Comment by myhndl** [comment]
Applying Blocker label because this blocks legitimate responses.

**Comment by Rizato** [comment]
I like maintaining the 100 block window in staging. After doing all my local tests, I really like to see the whole process go on staging before moving to prod. 

Increasing the timing on prod makes sense to me.

**Comment by scsich** [comment]
Okay, make it so. I'd like it so that Cuckoo isn't always broken and we can understand if the work that we've paid them for has been completed. This needs to move past discussion and into action.
