### ISSUE TITLE
Alerting: Low ETH Balance on Networks We Don't Own

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#37]
**Is your feature request related to a problem? Please describe.**
We can mint to our heart's content on our clique networks. Regrettably, we cannot on Rinkeby or Mainnet.

**Describe the solution you'd like**
Alert when ETH balance on Relay nodes drops below a configurable amount on:
* [ ] Rinkeby
* [ ] Mainnet

**Comment by aarongooch** [comment]
Created PR https://github.com/polyswarm/poly-mon/pull/68 based on polyswarm-client==1.0rc3 therefore we should not merge this until prod is updated.

**Comment by aarongooch** [comment]
monitors created let the alert party begin!
