### ISSUE TITLE
Alerting: Low NCT Balance

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#38]
**Is your feature request related to a problem? Please describe.**
Transactions are (soon to be) occurring exclusively on sidechains. Bounty managers should maintain a configurable balance on sidechain.

**Describe the solution you'd like**
We need alerts when:
* [ ] NCT balance on sidechain drops below a configurable amount
* [ ] NCT balance is insufficient on homechain to maintain the configurable amount on sidechain

Different thresholds for the two.

**Comment by aarongooch** [comment]
I set this up yesterday. It is a good start. 

https://app.datadoghq.com/monitors/7304549

Will probably need to use poly-mon to query for balances and set up DD gauges.

**Comment by aarongooch** [comment]
monitors created. Alerts for everyone!
